# Generated by Django 4.2.7 on 2025-12-29 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("canes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(blank=True, max_length=100)),
                ("telephone", models.CharField(max_length=20)),
                (
                    "type_contact",
                    models.CharField(
                        choices=[
                            ("FAMILLE", "Famille"),
                            ("AMI", "Ami"),
                            ("SOIGNANT", "Soignant"),
                            ("URGENCE", "Service d'urgence"),
                            ("AUTRE", "Autre"),
                        ],
                        default="FAMILLE",
                        max_length=20,
                    ),
                ),
                (
                    "priorite",
                    models.IntegerField(default=1, help_text="1 = priorité maximale"),
                ),
                (
                    "id_microcontroleur",
                    models.IntegerField(
                        blank=True,
                        help_text="ID du contact dans la mémoire du microcontrôleur",
                        null=True,
                    ),
                ),
                (
                    "synchro_avec_canne",
                    models.BooleanField(
                        default=False, help_text="Contact synchronisé avec la canne"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ajoute_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacts_ajoutes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "canne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="canes.canne",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["priorite", "nom"],
                "unique_together": {("canne", "telephone")},
            },
        ),
    ]
