# Generated by Django 4.2.7 on 2025-12-30 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("canes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("vitesse", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "canne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="canes.canne",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique Position",
                "ordering": ["-timestamp"],
            },
        ),
    ]
