# Generated by Django 4.2.7 on 2025-12-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="positionhistory",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="positionhistory",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="positionhistory",
            name="vitesse",
        ),
        migrations.AddField(
            model_name="positionhistory",
            name="lieu",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
