# Generated by Django 4.2.7 on 2025-12-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Canne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_gsm",
                    models.CharField(
                        help_text="Numéro du module GSM de la canne",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("MAINTENANCE", "En maintenance"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "derniere_communication",
                    models.DateTimeField(
                        blank=True,
                        help_text="Dernière communication avec la canne",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Canne",
                "verbose_name_plural": "Cannes",
            },
        ),
    ]
