# Generated by Django 4.2.7 on 2025-12-24 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("canes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_message",
                    models.CharField(
                        choices=[
                            ("COMMANDE", "Commande envoyée"),
                            ("REPONSE", "Réponse reçue"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contenu", models.TextField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("ENVOYE", "Envoyé"),
                            ("RECU", "Reçu"),
                            ("ERREUR", "Erreur"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("erreur_details", models.TextField(blank=True)),
                (
                    "canne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="canes.canne",
                    ),
                ),
                (
                    "envoye_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message SMS",
                "verbose_name_plural": "Messages SMS",
                "ordering": ["-timestamp"],
            },
        ),
    ]
